DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_type WHERE typname = 'payment_status'
	) THEN
		CREATE TYPE payment_status AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUNDED');
	END IF;
END $$;

ALTER TABLE no_show_orders
	ADD COLUMN IF NOT EXISTS payment_method TEXT NOT NULL DEFAULT 'TEST_CARD',
	ADD COLUMN IF NOT EXISTS payment_status payment_status NOT NULL DEFAULT 'PAID',
	ADD COLUMN IF NOT EXISTS paid_amount INTEGER NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
	ADD COLUMN IF NOT EXISTS payment_tx_id TEXT,
	ADD COLUMN IF NOT EXISTS payment_memo TEXT,
	ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ,
	ADD COLUMN IF NOT EXISTS failed_at TIMESTAMPTZ,
	ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMPTZ;
